### ISSUE TITLE
Tutorial – Ar (saw this in Store app, please check user app also)

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#103]
Tutorial numbering not in sync with a highlighted button icon
Highlighted icon not aligned 
Please provide tutorial text in file to translate properly

<img width="311" alt="image" src="https://user-images.githubusercontent.com/85341053/193816793-e4d90fce-1382-4060-a618-043578c715e2.png">

**Comment by Ahlam000** [comment]
Tutorial Text Service Provider
Home ->  'Provides the data of ongoing requests and orders. Also shows the average rating provided by the customers to your services',
My Booking->Access to all the details of upcoming services, past services.
Chat->Option to chat with the customer for the booked services
Notification->Reminders to the services
Profile->Access to personal informations

**Comment by Ahlam000** [comment]
tutorial text Customer app

Home -> 'Option to search for the services on the basis of categories and location.,
My Booking->Access to all the details of upcoming services, past services.
Chat->Option to chat with the service provider for the booked services
Notification->Reminders to the services and upcoming schedules
Profile->Access to personal informations

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/194559906-98816fbe-3d65-4575-8bcc-39e782c325dd.png)
@Ahlam000 still it is not covering  home icon both for english and arabic
