### ISSUE TITLE
We can use different icons for different types of notifications.

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#12]

**Comment by Mehulna** [comment]
@atul-gautam-au6  @Ahlam000  Explain me this what UI changes u need

**Comment by atul-gautam-au6** [comment]
We have multiple type of notification
1) booking related notification
      Booking submit
       Booking cancel
       Booking rejected
       Booking accepted
       Booking complete
2) coupon code generate notification
