### ISSUE TITLE
Sign up> add back button 

### ISSUE THREAD

**Issue by Anupriyabanger** [atul-gautam-au6/carwazi-issues#136]
On sign up screen, if i press back button the app is closing and when I return it's showing me the same screen with same information. 
<img width="137" alt="image" src="https://user-images.githubusercontent.com/109590553/195043089-a268be55-c8bf-4037-8108-c2744b08bd6a.png">

It should show this screen
<img width="153" alt="image" src="https://user-images.githubusercontent.com/109590553/195043673-c722ede1-afd8-4922-826f-fe03fbe7133c.png">

**Comment by Ahlam000** [comment]
return to sigjn from signup is already in the bottom

**Comment by rgnarok** [comment]
Closing this no pponter
