### ISSUE TITLE
we'll be Adding google map link for the user's addresss that will only be visible to mobile service providers and not to the non-mobile service providers.

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/carwazi-issues#143]

**Comment by rgnarok** [comment]
@Ahlam000  i have added a service but i am not able to see the location pin point on the detail on SP side, please share screenshot if it is working

**Comment by rgnarok** [comment]
@Ahlam000  again if the location is clickable then make it a URL as it is black so i cannot understand it is clickable please fix change the color of location to blue like a URL or give an option - Click here to check location on map
