### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#196]
Upon reschueling a booking through admin, the booking gets reschuled for the user but it disppear from SP side

**Comment by atul-gautam-au6** [comment]
@rgnarok  
![image](https://user-images.githubusercontent.com/58418713/220827184-ca6f55cb-07d1-4524-b478-c19a12bb3153.png)
https://admin.wazi1.com/order-management >> view order >> view order> > update date and time
