### ISSUE TITLE
User/Service provider

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#219]
Payables flow-
1. If the Card payment is done by the user, then Carwazi Team owes Service provider the amount - Service tax.
2. If the Payment mode is offline, then the Service provider needs to pay Service Tax to Carwazi. 
3. Change text to - Amount to be paid to

**Comment by Ahlam000** [comment]
![Screenshot_1682518480](https://user-images.githubusercontent.com/101115620/234604958-89d89c2f-f8d6-4374-b549-bd49d290f748.png)
@rgnarok  check pont 3 its already covered

**Comment by Ahlam000** [comment]
@atul-gautam-au6  please provide comment on first two points as you have done changes previously
