### ISSUE TITLE
Correct the text for the service provider where the data of amount to be send to carwazi or not

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#223]
@rgnarok please  share the text that needs to be changed

![Screenshot_1682518480](https://user-images.githubusercontent.com/101115620/234603873-bc071294-49c3-439f-9c24-c3e829de0a01.png)

**Comment by rgnarok** [comment]
@Ahlam000  change it to Amount to be paid by also please check and confirm that in case of a store the amount which need to be received from carwazi must be correct or vice versa

**Comment by Ahlam000** [comment]
![Screenshot_1683114932](https://user-images.githubusercontent.com/101115620/235909138-bef42065-e1bd-4f99-bf67-4341ac8b3cc3.png)
@rgnarok  done
