### ISSUE TITLE
Give the option to see the VAT applied on the customer end too Show the user the VAT and in case theere is an online paymwnt carwazi will pay the VAT to the store

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#224]

**Comment by rgnarok** [comment]
@atul-gautam-au6  @Ahlam000  please show the VAT value on the booking details page too for both SP and user once a booking is done by the user

**Comment by Ahlam000** [comment]
@rgnarok  vat i have put from user end in booking details page

**Comment by atul-gautam-au6** [comment]
@Ahlam000 pls share screenshot
