### ISSUE TITLE
V2 api create for multiple service for single order

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/carwazi-issues#232]

**Comment by atul-gautam-au6** [comment]
**User side api**
-  create booking
- get booking list for user
- get booking list for provider
- update booking
- Report api

Admin

- report api
- order api for user
- order api for provider
- get all order
- create order
- update order
- 
-

**Comment by Ahlam000** [comment]
- [x] User Booking Page UI will be replaced by Order Page
- [ ] On click of a Order Will Open Booking Page | Need Clarifitcation do we need user to rescedule and cancel order or a service here ui needs to be changed accordingly
- [ ]  Provider End |  ongoing orders ,upcoming and competed orders will be order based on click of any will open services ordered on that  order
- [ ]
