### ISSUE TITLE
Please comment out the export function in SP app reporting module

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#239]

**Comment by atul-gautam-au6** [comment]
{
    "successCode": 200,
    "successMessage": "report list",
    "list": [
        {
            "_id": null,
            "total": 4100,
            "costWithoutVAT": 4100,
            "costAndVAT": 4100,
            "costWithVatAndCommision": 4510,
            "totalCommision": 410,
            "totalOnline": 2000,
            "totalOffline": 2100,
            "amountAtProviderEnd": 0,
            "amountAtAdminEnd": 2000,
            "showExport": false
        }
    ]
} @Ahlam000   disable buttton based on "showExport": false
