### ISSUE TITLE
Comment out refer and earn  | Customer app

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#246]

**Comment by rgnarok** [comment]
![image](https://github.com/atul-gautam-au6/carwazi-issues/assets/85341053/438ecc61-00e9-44df-a2c1-aed8a6afe062)

**Comment by rgnarok** [comment]
![image](https://github.com/atul-gautam-au6/carwazi-issues/assets/85341053/a7ae9917-e4a6-4f61-84ef-862c071dd7ac)

**Comment by rgnarok** [comment]
![image](https://github.com/atul-gautam-au6/carwazi-issues/assets/85341053/728cb438-5215-4030-a34b-df47ca9a39f2)

**Comment by rgnarok** [comment]
![image](https://github.com/atul-gautam-au6/carwazi-issues/assets/85341053/3bd3042a-7ca6-4978-b97b-27e47f69b86c)

**Comment by Ahlam000** [comment]
https://drive.google.com/file/d/1tOHetsojVUR_2TkvgXYgp6zY3QlYH5Tj/view?usp=sharing
