### ISSUE TITLE
Wazi1.com >> Mobile view issues and irregularities

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#38]
![MicrosoftTeams-image (41)](https://user-images.githubusercontent.com/85341053/180133034-cac60612-6046-48ee-bd65-735d8c098786.png)
![MicrosoftTeams-image (42)](https://user-images.githubusercontent.com/85341053/180133051-968ddeda-fe60-4417-8210-e366807d0a31.png)
![MicrosoftTeams-image (43)](https://user-images.githubusercontent.com/85341053/180133055-2202b419-a6aa-4f6b-9bcf-873c8b7f4c49.png)
![MicrosoftTeams-image (44)](https://user-images.githubusercontent.com/85341053/180133058-ef22c0db-6e40-4270-bfcf-fe0cf3215ac6.png)
![MicrosoftTeams-image (45)](https://user-images.githubusercontent.com/85341053/180133062-acaa70a8-93ba-44ea-8357-3b3ce0e957b2.png)
![MicrosoftTeams-image (46)](https://user-images.githubusercontent.com/85341053/180133065-02e9411f-33bf-499d-bbd9-f6114dd710b7.png)
![MicrosoftTeams-image (47)](https://user-images.githubusercontent.com/85341053/180133069-fc3bce52-c5a4-41e7-8c4d-4e8ff09cfb61.png)
![MicrosoftTeams-image (48)](https://user-images.githubusercontent.com/85341053/180133072-6b3128f3-5581-481d-a5ce-dc1fb059f964.png)
![MicrosoftTeams-image (49)](https://user-images.githubusercontent.com/85341053/180133073-6471aea6-ff70-4da4-9667-b3edbe586c2a.png)
![MicrosoftTeams-image (50)](https://user-images.githubusercontent.com/85341053/180133075-40a7de28-ed51-41d8-9e70-da49933d5568.png)

**Comment by atul-gautam-au6** [comment]
@bidyut-majumdar pls update the status..?

**Comment by VayuzBidyut** [comment]
Anoop has worked on it yesterday, so adding review required.

**Comment by atul-gautam-au6** [comment]
@rgnarok pls take it forword
