### ISSUE TITLE
PinPoint location missing(Customer App)

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#55]

**Comment by Ahlam000** [comment]
Need clarity for this as this is not in the requirements

**Comment by rgnarok** [comment]
@Ahlam000  pini point not happening it is just map coming up and also location which i am adding in search not coming up

**Comment by rgnarok** [comment]
@Ahlam000 i cannot click on pinpoint and put it to different location and finalise the location where i put the location pin point

**Comment by rgnarok** [comment]
@Ahlam000  still not working pin point is not draggable what i mean to say check zomato for reference

**Comment by atul-gautam-au6** [comment]
- [ ] when click on location, map should be render with my current location and pin pointed with zoom-In functionality
- [ ] In map bottom must have my current location name and it will auto changes when drag the the map and set the location on  marker(marker also draggable)(Check the screenhsot)
- [ ] Map bottom  shit have change and confirm location(Check the screenshot)
- [ ] Once search the location using change location feature it will re-render map with animation
- [ ] Once confirm location ,location would be set on home screen
- [
![WhatsApp Image 2022-09-08 at 10 49 53 AM (1)](https://user-images.githubusercontent.com/58418713/189040525-9088176b-2f03-46c6-a49e-85c9a41ddfdd.jpeg)
![WhatsApp Image 2022-09-08 at 10 49 53 AM](https://user-images.githubusercontent.com/58418713/189040535-e13e61bb-dd27-492b-a7d8-9800b93ca621.jpeg)

**Comment by atul-gautam-au6** [comment]
@Ahlam000
