### ISSUE TITLE
 Old Chat history is appearing when a new chat is starting for a new booking should disappear on the specified time " 2 days" as agreed. (Customer App)

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#56]

**Comment by rgnarok** [comment]
@Ahlam000  @atul-gautam-au6 I am starting a message and it is not going in the chat section it os showing nothing in listing

**Comment by atul-gautam-au6** [comment]
@rgnarok  please share the screen-shot here

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/188880384-289f17a0-39dc-4006-a44a-d075e1afb3fd.png)
![image](https://user-images.githubusercontent.com/85341053/188880416-172e0dd5-9ab5-4387-ac6b-63cab59f5f02.png)
