### ISSUE TITLE
invoice:  Saudi regulations should be followed. Also,  there should be a method to extract Service Provider Vat number, Address, and Phone number. (Admin)

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#58]

**Comment by rgnarok** [comment]
Saudi Arabian VAT invoice requirements

VAT invoices must be issued for all taxable supplies and/or related payments
Invoices must be issued by at least the 15th of the month following the taxable supply
Invoices should include the following details:
Date of invoice (and date of supply if different)
Unique, sequential invoice number
Tax ID number of the supplier
Name and address of the supplier and customers
Description and quantity of the goods supplies; nature of services provided
Gross, VAT and net values of supply
VAT rate applied, and explanation where not the standard rate
Simplified invoices are permitted where the taxable supply is below Riyals 1,000; this excludes the VAT calculation and address of the customer
Electronic invoices must be issued where prescribed by the tax authorities
Invoice credit or debit notes must contain a reference to the original sales invoice number, plus any details of a discount

**Comment by technicalbirdVayuz** [comment]
- [x] VAT invoices must be issued for all taxable supplies and/or related payments
- [ ] Invoices must be issued by at least the 15th of the month following the taxable supply
- [x] Invoices should include the following details:
- [x] Date of invoice (and date of supply if different)
- [x] Unique, sequential invoice number
- [x] Tax ID number of the supplier
- [x] Name and address of the supplier and customers
- [x] Description and quantity of the goods supplies; nature of services provided
- [x] Gross, VAT and net values of supply
- [x] VAT rate applied, and explanation where not the standard rate
- [ ] Electronic invoices must be issued where prescribed by the tax authorities
- [x] Simplified invoices are permitted where the taxable supply is below Riyals 1,000; this excludes the VAT calculation and address of the customer
- [ ] Invoice credit or debit notes must contain a reference to the original sales invoice number, plus any details of a discount

**Comment by rgnarok** [comment]
@atul-gautam-au6  what is required?

**Comment by rgnarok** [comment]
@atul-gautam-au6  invoice unique number is not added please add

**Comment by atul-gautam-au6** [comment]
@rgnarok done. please check
