### ISSUE TITLE
Invoice section: Does not reflect actual details. When generating an invoice based on a specified date it does not reflect any information.  (Admin)

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#60]

**Comment by rgnarok** [comment]
@atul-gautam-au6  not reflecting any detail only empty pages
client send this to us
Saudi Arabian VAT invoice requirements

VAT invoices must be issued for all taxable supplies and/or related payments
Invoices must be issued by at least the 15th of the month following the taxable supply
Invoices should include the following details:
Date of invoice (and date of supply if different)
Unique, sequential invoice number
Tax ID number of the supplier
Name and address of the supplier and customers
Description and quantity of the goods supplies; nature of services provided
Gross, VAT and net values of supply
VAT rate applied, and explanation where not the standard rate
Simplified invoices are permitted where the taxable supply is below Riyals 1,000; this excludes the VAT calculation and address of the customer
Electronic invoices must be issued where prescribed by the tax authorities
Invoice credit or debit notes must contain a reference to the original sales invoice number, plus any details of a discount
