### ISSUE TITLE
Service Management: Upon adding a new service to SP, it does not show on the SP page.(Admin)

### ISSUE THREAD

**Issue by Ahlam000** [atul-gautam-au6/carwazi-issues#68]

**Comment by atul-gautam-au6** [comment]
`
![Screenshot_2022-08-25_17-20-36](https://user-images.githubusercontent.com/58418713/186657300-a4c5715c-97fd-4b54-a39b-a7f59b343cc7.png)
![Screenshot_2022-08-25_17-19-44](https://user-images.githubusercontent.com/58418713/186657312-5b3c341d-3677-4de0-b470-52fa9ead8cb4.png)
`

**Comment by atul-gautam-au6** [comment]
@Ahlam000  app is showing white screen when i open my server page on this creds
email : autoxpress@mailinator.com
pass: Pass@123#

please have a look
