### ISSUE TITLE
Service provider >> I can see a red dot on chat but nothing is coming up listing of chat

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#75]

**Comment by atul-gautam-au6** [comment]
could you please attach the screen-shot here @rgnarok

**Comment by rgnarok** [comment]
@atul-gautam-au6 try sending a message from user Kush11@mailinator.com pass - Kush96agra@
Service provider - Kush11@mailinator.com pass - Kush96agra@ (Rgnrok)
My service is completed but I am sending messages I a receiving the notification but in the chat listing nothing is coming up.
Also, this is the case for red dot too as red dot comes but no new message, please fix
![image](https://user-images.githubusercontent.com/85341053/188878785-fdbd07f7-155e-448c-b940-3444eb740a37.png)

![image](https://user-images.githubusercontent.com/85341053/188878828-9706726d-2314-447b-ae74-63194eb38e42.png)
