### ISSUE TITLE
593 and 877

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#85]
Wrong positioning of the tutorial box on icons

**Comment by atul-gautam-au6** [comment]
![InkedScreenshot_2022-09-15-11-32-30-593_com carwazi](https://user-images.githubusercontent.com/58418713/191424850-a4267f61-1c78-4869-bf0e-6b45e811baf9.jpg)
![InkedScreenshot_2022-09-19-14-31-30-877_com carwazi](https://user-images.githubusercontent.com/58418713/191424882-0bf2661a-bacb-45be-8908-89e714218550.jpg)
