### ISSUE TITLE
signup email validation is not coming after giving wrong email

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/carwazi-issues#9]

**Comment by rgnarok** [comment]
![image](https://user-images.githubusercontent.com/85341053/180143761-6f679476-ec71-4b8c-8f11-ff2402d82324.png)
When I add a wrong email like in the screenshot and then I add a phone number, the error message disappears, but i cannot sign in. It must show the error message until the email is correct
