### ISSUE TITLE
Chat SP and Customer

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/carwazi-issues#99]
Old Chat history is appearing when a new chat is starting for a new booking should disappear on the specified time " 2 days" as agreed.  Translation should not apply to chat.

**Comment by rgnarok** [comment]
@Ahlam000  there is no chat option on the accepted service for the user kush111@mailinator.com Kush96agra@
Not able to test 

![image](https://user-images.githubusercontent.com/85341053/194557455-ea2ad1df-ca2c-44de-9e60-42db01ee09ff.png)

**Comment by Ahlam000** [comment]
@rgnarok  please check the date of booking 13 sept as time limit of chat is 48 hours only
